dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - node
addons:
  firefox: latest-esr
cache:
  directories:
    - node_modules
before_install:
  - 'if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e ''console.log(process.version)'') ]; then npm rebuild --update-binary && node -e ''console.log(process.version)'' > node_modules/.last-node-version; fi'
before_script:
  - npm install polymer-cli
  - yarn install
  - $(npm bin)/polymer lint
script: xvfb-run $(npm bin)/polymer test --npm

